name: edgelab

channels:
  - defaults
  - pytorch

dependencies:
  - cudatoolkit=11.7
  - python=3.8
  - pytorch=2.0.0
  - pytorch-cuda=11.7
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - pip=23.0.1
  - pip:
    - -r requirements/base.txt
    - -r requirements/pytorch.txt
    - -r requirements/inference.txt